language: node_js
node_js:
  - "6"
addons:
  postgresql: "9.5"
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
env:
  global:
    - PGHOST=localhost
    - PGDATABASE=travis_ci_test
    - PGUSER=postgres
    - PGPASSWORD=
  
